### ISSUE TITLE
(node:17124) UnhandledPromiseRejectionWarning: TypeError [REQ_RESOURCE_TYPE]: The resource must be a string, Buffer or a valid file stream.

### ISSUE THREAD

**Issue by Oxadeum** [Mr-KayJayDee/discord-image-generation#5]
Hello ! ^^

I have a problem with my code
The error is in the title

My code : 

[Code](https://sourceb.in/1b10697480)

**Comment by Mr-KayJayDee** [comment]
Hello, change ```js
let lisaImage = new DIG.LisaPresentation().getImage(textInImage);```

with 

```let lisaImage = await new DIG.LisaPresentation().getImage(textInImage);```

**Comment by Oxadeum** [comment]
Thank's for your help ^^

And for the error in my command delete ?

[Code Delete](https://sourceb.in/fc028dc1cf)

**Comment by Mr-KayJayDee** [comment]
Your welcome, what is the error on this one ?

**Comment by Oxadeum** [comment]
(node:16692) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'displayAvatarURL' of undefined

**Comment by Mr-KayJayDee** [comment]
message.author doesn't have a .user property

**Comment by Oxadeum** [comment]
Thank's you very much, your modules is so good :)

**Comment by Mr-KayJayDee** [comment]
Haha, thank you, feel free to open a new issue if you have another question. 😉
