### ISSUE TITLE
(node:17124) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'displayAvatarURL' of undefined

### ISSUE THREAD

**Issue by Oxadeum** [Mr-KayJayDee/discord-image-generation#6]
Hello ! ^^

I have a problem with my code
The error is in the title

My code : 

[Code](https://sourceb.in/fc028dc1cf)

**Comment by Mr-KayJayDee** [comment]
Dupe of [Issue 5](https://github.com/Mr-KayJayDee/discord-image-generation/issues/5)
